### ISSUE TITLE
Installation broken? 

### ISSUE THREAD

**Issue by idoDavid** [jupyterlab/jupyter-renderers#107]
Hi,

Trying to install the plotly extension by `jupyter labextension install @jupyterlab/plotly-extension`, I'm getting an `UnboundLocalError: local variable 'proc' referenced before assignment` Error.

I'm on jupyter 4.4.0, python 3.5 and anaconda installation, am I doing something wrong?

**Comment by herbzhao** [comment]
I get a different error:     

kwargs = {'name': self.extra_args[1]}
IndexError: list index out of range

**Comment by jvaldiviezo9** [comment]
I had this error: error Couldn't find match for "83b1a3e5837d785af582efd5ed1a212f2df6a4ae" in "_c" for "https://github.com/mapbox/mapbox-gl-style-spec.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I installed nodejs via pip and using https://anaconda.org/conda-forge/nodejs with the same result

I'm using anaconda, 

plotly 2.4.1
jupyterlab 0.31.10  

this issue occurs in windows and macos

**Comment by gnestor** [comment]
@blink1073 Does this sound familiar?

**Comment by idoDavid** [comment]
Some background:

I'm using python 3.5 with anaconda. Stacktrace:

`> npm pack @jupyterlab/plotly-extension
Traceback (most recent call last):
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 73, in run
    proc = Popen(cmd, **kwargs)
  File "/Users/idodavid/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Users/idodavid/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm': 'npm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/idodavid/anaconda3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 168, in start
    super(LabExtensionApp, self).start()
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 58, in start
    for arg in self.extra_args]
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 58, in <listcomp>
    for arg in self.extra_args]
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 100, in install_extension
    return IOLoop.instance().run_sync(func)
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 138, in install_extension_async
    yield run([get_npm_name(), 'pack', extension], cwd=target, logger=logger, abort_callback=abort_callback)
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/idodavid/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 86, in run
    proc.wait()
UnboundLocalError: local variable 'proc' referenced before assignment`

**Comment by idoDavid** [comment]
Managed to solve it with the info (here)[https://github.com/bokeh/jupyterlab_bokeh/issues/5]

just `conda install nodejs` and then try the installation again.

**Comment by gnestor** [comment]
Great! 

@jvaldiviezo9 Can you try installing npm via `conda install nodejs` and see if that resolves you issue?

**Comment by jvaldiviezo9** [comment]
@gnestor The solution in my case was that Git was not installed, that solved my problem

**Comment by gnestor** [comment]
@jvaldiviezo9 Ah, git. Would not have been one of my first guesses 👍
