### ISSUE TITLE
cannot install on Windows 10

### ISSUE THREAD

**Issue by Isaacsh** [jupyterlab/jupyter-renderers#127]
Have already installed nodejs 8.9.3 with conda, bumped into the following error when trying to install `plotly-extension`:

```
> C:\Users\<>\AppData\Local\Continuum\anaconda3\npm.CMD pack @jupyterlab/plotly-extension
jupyterlab-plotly-extension-0.14.5.tgz
Traceback (most recent call last):

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 71, in start
    ans = self.run_task()

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 100, in <listcomp>
    for arg in self.extra_args

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\commands.py", line 210, in install_extension
    return handler.install_extension(extension)

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\commands.py", line 347, in install_extension
    info = self._install_extension(extension, tempdir)

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\tempfile.py", line 807, in __exit__
    self.cleanup()

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())

  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<>\\AppData\\Local\\Temp\\tmpet5pksuo'


Errored, use --debug for full output:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<>\\AppData\\Local\\Temp\\tmpet5pksuo'
```

Any words of wisdom would be appreciated.

**Comment by darkniobe** [comment]
I ran into this exact problem with Nodejs version 10. It appears to be similar to a problem noted in issue #132 . I was able to resolve it by downloading Nodejs 6 from here: https://nodejs.org/download/release/v6.14.4/node-v6.14.4-win-x64.zip
then extracting it and putting it in my path somewhere before Nodejs 10.

**Comment by jmrouet** [comment]
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<>\\AppData\\Local\\Temp\\tmpet5pksuo'

What worked for me on Win10, was to temporarily patch the shutil.py module in my conda environment
in <myenv>/Lib/shutil.py
look for method:
def _rmtree_unsafe(path, onerror):
and replace the last line:
    onerror(os.rmdir, path, sys.exc_info())
with
    if True: # changed temporarily to solve a jupyterinstall issue
        print("os.rmdir: ignoring OSError")
        pass
    else:
        onerror(os.rmdir, path, sys.exc_info())

**Comment by vidartf** [comment]
Note that this should be fixed from Python 3.8 onwards.

**Comment by MaximilianHoffmann** [comment]
Doesn't seem fixed for me

**Comment by vidartf** [comment]
I'm thinking of this being included now (https://bugs.python.org/issue26660).

**Comment by vidartf** [comment]
That might be different though (another process using vs access denied)... :-/

**Comment by asodeur** [comment]
This is a different issue, indeed. Seems hard to believe (rightly so) for non-Windows developers that `rmtree` is working async in Windows and there is no easy way to tell if it actually has finished.

The usual strategy to cope with this is some sort of exponential backoff. See [this](https://bugs.python.org/issue15496) (and corresponding [PR](https://hg.python.org/cpython/rev/c863dadc65eb)) for essentially the same issue hitting Python's testsuite.

**Comment by bjudkewitz** [comment]
Command line shutil.py patch, if you are using conda:
`rename %CONDA_PREFIX%\Lib\shutil.py shutil.bak`
`powershell -Command "(gc %CONDA_PREFIX%\Lib\shutil.bak) -replace 'onerror\(os.rmdir, path, sys.exc_info\(\)\)', 'print(\"os.rmdir: ignoring OSError\") #$&' | Out-File -encoding ASCII %CONDA_PREFIX%\Lib\shutil.py"`
Undo:
`copy %CONDA_PREFIX%\Lib\shutil.bak %CONDA_PREFIX%\Lib\shutil.py`
