### ISSUE TITLE
Plotly ext install hanging up on package resolution

### ISSUE THREAD

**Issue by dvandagriff** [jupyterlab/jupyter-renderers#131]
Howdy folks, 

Not sure if this is the place to put this but I'm struggling with installing the plotly renderer. It keeps hanging up on 

```
drew:~$ sudo jupyter labextension install @jupyterlab/plotly-extension
> /usr/local/bin/npm pack @jupyterlab/plotly-extension
jupyterlab-plotly-extension-0.16.0.tgz
> node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:23151) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
⢀ @jupyterlab/plotly-extension@file:../extensions/jupyterlab-plotly-extension-0.16.0.tgz
```
for like forever. Even left it going for like 2 hours to see what would happen. I'd have to ultimately cmd+C out of there. I am not a dev so forgive me if I'm just dumb and this is an easy fix.

Not sure if this will help either but here is some traceback context when I cmd+C.
```
[1/4] 🔍  Resolving packages...
⢀ @jupyterlab/plotly-extension@file:../extensions/jupyterlab-plotly-extension-0.16.0.tgz^CTraceback (most recent call last):
  File "/anaconda3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 213, in start
    super(LabExtensionApp, self).start()
  File "/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 75, in start
    logger=self.log, command=command)
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 259, in build
    command=command, clean_staging=clean_staging)
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 400, in build
    self._run(['node', YARN_PATH, 'install'], cwd=staging)
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1278, in _run
    return proc.wait()
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/process.py", line 108, in wait
    time.sleep(1.)
KeyboardInterrupt
```

Jupyter Lab, node, and plotly are all up to date.

```
drew:~$ jupyter lab --version
0.32.1
drew:~$ ipython
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import plotly

In [2]: plotly.__version__
Out[2]: '2.5.1'

In [3]:                                                                                                                                     
Do you really want to exit ([y]/n)? y
drew:~$ node --version
v10.0.0
```

Thanks for any insight.

**Comment by jwhendy** [comment]
Dammit. I just searched on and off all day for incantations of "jupyterlab extension install hangs" and similar and didn't see this. I guess I should have checked here first, but assumed it was a fringe/unique problem.

I've got the exact same issue. Looks like this indefinitely when I try to install:
```
$ jupyter labextension install @jupyterlab/plotly-extension
> /usr/bin/npm pack @jupyterlab/plotly-extension
npm notice 
npm notice 📦  @jupyterlab/plotly-extension@0.16.0
npm notice === Tarball Contents === 
npm notice 0     package         
npm notice 2.4kB README.md       
npm notice 0     lib             
npm notice 1.2kB package.json    
npm notice 0     style           
npm notice 1.3kB lib/index.d.ts  
npm notice 4.7kB lib/index.js    
npm notice 546B  style/index.css 
npm notice 1.7kB style/plotly.svg
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/plotly-extension            
npm notice version:       0.16.0                                  
npm notice filename:      jupyterlab-plotly-extension-0.16.0.tgz  
npm notice package size:  4.3 kB                                  
npm notice unpacked size: 11.8 kB                                 
npm notice shasum:        8426a56c6fc3818c4015df33db5c164edafacf91
npm notice integrity:     sha512-MLDMSe5cXUx/U[...]14383uemZUL3g==
npm notice total files:   9                                       
npm notice 
jupyterlab-plotly-extension-0.16.0.tgz
> node /home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:22182) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
⠂ @jupyterlab/plotly-extension@file:../extensions/jupyterlab-plotly-extension-0.16.0.tgz
```

When I `Ctrl-c` I get this:
```
^CTraceback (most recent call last):
  File "/home/jwhendy/.local/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/jwhendy/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 213, in start
    super(LabExtensionApp, self).start()
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 75, in start
    logger=self.log, command=command)
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 259, in build
    command=command, clean_staging=clean_staging)
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 400, in build
    self._run(['node', YARN_PATH, 'install'], cwd=staging)
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 1278, in _run
    return proc.wait()
  File "/home/jwhendy/.local/lib/python3.6/site-packages/jupyterlab/process.py", line 108, in wait
    time.sleep(1.)
KeyboardInterrupt
```
Misc details:
```
$ jupyter --version
4.4.0
$ jupyter notebook --version
5.4.1
$ jupyter lab --version
0.32.1
$ node --version
v10.0.0
$ npm --version
6.0.0

>>> plotly.__version__
'2.5.1'
```

**Comment by dvandagriff** [comment]
I have tried this on 2 different machines (My work Mac and home PC, both using Anaconda distro) and getting the same results.

**Comment by gnestor** [comment]
I am able to reproduce this using Node 10. Downgrading to Node 9 fixes the "hang on resolving packages step of `yarn install`".

**Comment by jwhendy** [comment]
The install works for me using Node 9 as well. On arch, I downgraded to 2018-03 versions from the Arch Linux Archive:
- `icu` from [core](https://archive.archlinux.org/repos/2018/03/07/core/os/x86_64/)
- `nodejs` from [community](https://archive.archlinux.org/repos/2018/03/07/community/os/x86_64/)

**Comment by dvandagriff** [comment]
Downgraded to node 6 using Brew from #132 and it worked with no issues. Thank!!!

**Comment by gnestor** [comment]
Good to hear!
