### ISSUE TITLE
[WinError 32]

### ISSUE THREAD

**Issue by antvig** [jupyterlab/jupyter-renderers#136]
Hi,

I'm experiencing a WinError32 issue while installing vega2-extension.
And I'm in admin mode with all access...

```
> C:\Anaconda3\npm.CMD pack @jupyterlab/vega2-extension
jupyterlab-vega2-extension-0.16.0.tgz
Traceback (most recent call last):

  File "C:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 71, in start
    ans = self.run_task()

  File "C:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "C:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 100, in <listcomp>
    for arg in self.extra_args

  File "C:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 227, in install_extension
    return handler.install_extension(extension)

  File "C:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 366, in install_extension
    info = self._install_extension(extension, tempdir)

  File "C:\Anaconda3\lib\tempfile.py", line 807, in __exit__
    self.cleanup()

  File "C:\Anaconda3\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)

  File "C:\Anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\Anaconda3\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())

  File "C:\Anaconda3\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)

PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\SESA40~1\\AppData\\Local\\Temp\\tmpl6fltfxv'
```

**Comment by gnestor** [comment]
Try shutting down the jupyter notebook server and then installing.

**Comment by antvig** [comment]
Still the same issue ...
