### ISSUE TITLE
jlpm run build failed

### ISSUE THREAD

**Issue by TK-21st** [jupyterlab/jupyter-renderers#138]
- Nodejs version: v9.11.1
- jlpm version: 1.7.0

Cloned latest commit

tried 

```
jlpm            // no error
jlpm build  // failed
```

full output trace is 
```
$ jlpm build

yarn run v1.7.0
$ lerna run --parallel build
lerna info version 2.11.0
lerna info versioning independent
lerna info run in 5 package(s): npm run build
lerna ERR! execute callback with error
lerna ERR! Error: spawn yarn ENOENT
lerna ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
lerna ERR!     at onErrorNT (internal/child_process.js:379:16)
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:178:19)
lerna ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
lerna ERR!     at startup (internal/bootstrap/node.js:201:19)
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
{ Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'run', 'build' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by frmdstryr** [comment]
Try with node-js 8. I had lots of issues with node-js 10, switched back to 8 and everything is working now.

**Comment by gnestor** [comment]
Yes, this looks like a Node 10 issue. This may be resolved on jupyterlab master but until a fix is published, try downgrading to node < 10.
