### ISSUE TITLE
Travis CI build failure

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyter-renderers#145]
I've observed that the travis builds have been failing due to the following:

```
Error: Cannot find module '/home/travis/miniconda/lib/python3.6/site-packages/jupyterlab/chrome-test.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

This is the result of running `python -m jupyterlab.selenium_check` in `.travis.yml`. I assume something has changed in jupyterlab which requires that we change our end. However, jupyterlab runs the same command in its travis script: https://github.com/jupyterlab/jupyterlab/blob/master/scripts/travis_script.sh#L92

**Comment by gnestor** [comment]
Should be fixed by https://github.com/jupyterlab/jupyterlab/pull/4989
