### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dfernan** [jupyterlab/jupyter-renderers#45]
I tried installing the dev version but I am getting an error and I am  unsure how to debug it.
I am running:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
npm is already the newest version (3.5.2-0ubuntu4).
npm is already the newest version (3.5.2-0ubuntu4).

And then I do:
`npm install`

But get this error:
```
> undefined install /home/ubuntu/jupyter-renderers
> lerna bootstrap --hoist

/usr/bin/env: ‘node’: No such file or directory

npm WARN jupyter-renderers No repository field.
npm WARN jupyter-renderers No license field.
npm ERR! Linux 4.4.0-1035-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! undefined install: `lerna bootstrap --hoist`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the undefined install script 'lerna bootstrap --hoist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap --hoist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/jupyter-renderers/npm-debug.log
```

**Comment by blink1073** [comment]
Hi @dfernan, I've not seen that before.  Are you able to install `npm 4`?  Assuming write access, `npm install -g npm@4` should work.

**Comment by dfernan** [comment]
Hi @blink1073 thanks for your help.  

I am still getting an error, the install worked though, the part that didn't work is the build now.

I do:
```
cd jupyter-renderers
ubuntu@ip-10-1-73-206:~/jupyter-renderers$ sudo npm install -g npm@4
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib
└── npm@4.6.1
```
(this part worked now.)
```
ubuntu@ip-10-1-73-206:~/jupyter-renderers$ sudo npm run build

> @ build /home/ubuntu/jupyter-renderers
> lerna run build

lerna info version 2.4.0
```
(this part did not work)

The log file for the `sudo npm run build` is this one:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.6.1
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 silly lifecycle @~prebuild: no script for prebuild, continuing
7 info lifecycle @~build: @
8 verbose lifecycle @~build: unsafe-perm in lifecycle true
9 verbose lifecycle @~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/jupyter-renderers/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle @~build: CWD: /home/ubuntu/jupyter-renderers
11 silly lifecycle @~build: Args: [ '-c', 'lerna run build' ]
12 silly lifecycle @~build: Returned: code: 1  signal: null
13 info lifecycle @~build: Failed to exec build script
14 verbose stack Error: @ build: `lerna run build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid @
16 verbose cwd /home/ubuntu/jupyter-renderers
17 verbose Linux 4.4.0-1035-aws
18 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "build"
19 verbose node v4.2.6
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error @ build: `lerna run build`
23 error Exit status 1
24 error Failed at the @ build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by blink1073** [comment]
It looks like we need another `npm install` from the repo directory.  Can you please try removing any existing `node_modules` from that folder and running `npm install` again?

**Comment by gnestor** [comment]
@dfernan Any luck?

**Comment by gnestor** [comment]
With the latest commit, we have switched over to using [yarn](https://github.com/yarnpkg/yarn) for node package management, so try [installing yarn](https://yarnpkg.com/en/docs/install), pulling the latest master, and running `yarn install`.

**Comment by gnestor** [comment]
Closing this due to inactivity. Feel free to reopen if the issue persists.
