### ISSUE TITLE
Error installing plotly-extension on Windows

### ISSUE THREAD

**Issue by robot-uprising** [jupyterlab/jupyter-renderers#67]
When I try to install plotly-extension to jupyterlab on Windows 10, I get the following error:

(Keras_learn) C:\Users\xxxxxxx>jupyter labextension install @jupyterlab/plotly-extension
> npm.cmd pack @jupyterlab/plotly-extension
'npm.cmd' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\Scripts\jupyter-labextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyterlab\labextensions.py", line 168, in start
    super(LabExtensionApp, self).start()
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyterlab\labextensions.py", line 58, in start
    for arg in self.extra_args]
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyterlab\labextensions.py", line 58, in <listcomp>
    for arg in self.extra_args]
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyterlab\commands.py", line 100, in install_extension
    return IOLoop.instance().run_sync(func)
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\tornado\ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "C:\Users\xxxxxxx\AppData\Local\Continuum\anaconda3\envs\Keras_learn\lib\site-packages\jupyterlab\commands.py", line 140, in install_extension_async
    fname = os.path.basename(glob.glob(pjoin(target, '*.*'))[0])
IndexError: list index out of range

**Comment by dhirschfeld** [comment]
> 'npm.cmd' is not recognized as an internal or external command,

Do you have npm (node) installed? If not, it can be installed with:
```
conda install nodejs
```

**Comment by robot-uprising** [comment]
That fixed it.  Thanks.

**Comment by dhirschfeld** [comment]
@robot-uprising - feel free to close this if your issue is fixed - saves the maintainers from having to do it themselves. I'd do it but t I don't have write access myself without which you can't close others' issues.
