### ISSUE TITLE
Error installing vega3 extension on windows

### ISSUE THREAD

**Issue by davidanthoff** [jupyterlab/jupyter-renderers#91]
This is with the latest jupyter lab beta (0.31.1)

Here is what I get:
````
C:\Users\david> jupyter labextension install @jupyterlab/vega3-extension
> "C:\Program Files\nodejs\npm.CMD" pack @jupyterlab/vega3-extension
jupyterlab-vega3-extension-0.14.1.tgzwser when you connect for the first time,
> node C:\Users\david\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[-/3] ⠐ waiting...
[2/3] ⠐ canvas: using node@8.9.4 | win32 | x64
[3/3] ⠈ canvas-prebuilt: node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v57-win32-x64.tar.gz
[-/3] ⠈ waiting...
warning Error running install script for optional dependency: "C:\\Users\\david\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: C:\\Users\\david\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas\nOutput:\nC:\\Users\\david\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.4 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Can't find Python executable \"C:\\Users\\david\\Anaconda3\\python.EXE\", you can set the PYTHON env variable.\ngyp ERR! stack     at PythonFinder.failNoPython (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:483:19)\ngyp ERR! stack     at PythonFinder.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:508:16)\ngyp ERR! stack     at C:\\Program Filessuccess Saved lockfile.
Done in 50.41s.
> node C:\Users\david\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:181
        var idxQuery = identifier.indexOf("?");
                                  ^

TypeError: Cannot read property 'indexOf' of null
    at Resolver.parse (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:181:28)
    at Resolver.<anonymous> (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\ParsePlugin.js:14:25)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\Tapable.js:256:13)
    at runNormal (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:130:20)
    at Resolver.doResolve (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:116:3)
    at Resolver.<anonymous> (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:12)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\Tapable.js:256:13)
    at runNormal (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:130:20)
    at Resolver.doResolve (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:116:3)
    at Resolver.<anonymous> (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\AliasFieldPlugin.js:44:12)
    at next (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\Tapable.js:254:14)
    at Resolver.<anonymous> (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\ConcordModulesPlugin.js:23:28)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\Tapable.js:256:13)
    at runNormal (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:130:20)
    at Resolver.doResolve (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:116:3)
    at DescriptionFileUtils.loadDescriptionFile (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:39:14)
    at C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:48:12
    at C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\forEachBail.js:29:14
    at onJson (C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:39:5)
    at C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:17:6
    at C:\Users\david\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:70:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
C:\Users\david>
````

**Comment by domoritz** [comment]
Hmm, I'm getting a similar error. I'm investigating.

**Comment by domoritz** [comment]
I think it's a bug in something with webpack: https://github.com/webpack/enhanced-resolve/issues/118. With Webpack 1, I don't get any errors.

**Comment by pelotom** [comment]
FYI I filed a ticket with Vega: https://github.com/vega/vega/issues/1118

**Comment by pelotom** [comment]
Actually I think the root issue is https://github.com/vega/vega-canvas/issues/1.

**Comment by davidanthoff** [comment]
Just verified that this is fixed now. Thanks!
